name: networks

desc: Neighborhood Accessibility Variables

model_type: networks

node_col: node_id

variable_definitions:

  - name: ave_parcel_size
    dataframe: parcels
    varname: parcel_acres
    radius: 800
    aggregation: average
    decay: flat
    apply: np.log1p

  - name: mean_nonres_rent_2000m
    aggregation: average
    dataframe: buildings
    decay: flat
    filters:
    - non_residential_sqft > 0
    radius: 2000
    varname: nonres_rent_per_sqft

  - name: jobs_1500m
    dataframe: jobs
    radius: 1500
    apply: np.log1p
    
  - name: jobs_800m
    dataframe: jobs
    radius: 800
    apply: np.log1p
    
  - name: jobs_400m
    dataframe: jobs
    radius: 400
    apply: np.log1p
    
  - name: ave_income
    dataframe: households
    varname: income
    radius: 1500
    aggregation: average
    decay: flat
    apply: np.log1p
    
  - name: ave_age_of_head_1500m
    dataframe: households
    varname: age_of_head
    radius: 1500
    aggregation: average
    decay: flat
    apply: np.log1p
    
  - name: ave_children_1500m
    dataframe: households
    varname: children
    radius: 1500
    aggregation: average
    decay: flat
    
  - name: ave_year_built_1500m
    dataframe: buildings
    varname: year_built
    radius: 1500
    aggregation: average
    decay: flat
    apply: np.log1p
    
  - name: population_400m
    dataframe: households
    varname: persons
    radius: 400
    aggregation: sum
    decay: flat
    apply: np.log1p

  - name: jobs_3000m
    dataframe: jobs
    radius: 3000
    decay: flat
    
  - name: households_3000m
    dataframe: households
    radius: 3000
    decay: flat
    
  - name: residential_units_3000m
    dataframe: buildings
    varname: residential_units
    radius: 3000
    aggregation: sum
    decay: flat
    
  - name: residential_units_1500m
    dataframe: buildings
    varname: residential_units
    radius: 1500
    aggregation: sum
    decay: flat
    
  - name: residential_units_800m
    dataframe: buildings
    varname: residential_units
    radius: 800
    aggregation: sum
    decay: flat