null:
    filters:
    - age_of_head < 40
    fitted_parameters:
    - -5.111984721917692
    - 0.12937080499546547
    - -7.380928627907898e-06
    - 0.386911210479455
    - -5.0005270183615935e-06
    model_expression: children ~ age_of_head + income + cars + residential_sqft
    name: null
    out_column: null
    out_tables: null
    out_transform: null
    out_value_false: nothing
    out_value_true: -1
    summary_table: "                           Logit Regression Results          \
        \                 \n==============================================================================\n\
        Dep. Variable:               children   No. Observations:                \
        \ 4776\nModel:                          Logit   Df Residuals:            \
        \         4771\nMethod:                           MLE   Df Model:        \
        \                    4\nDate:                Wed, 14 Mar 2018   Pseudo R-squ.:\
        \                 0.08767\nTime:                        21:09:30   Log-Likelihood:\
        \                -2393.6\nconverged:                       True   LL-Null:\
        \                       -2623.6\n                                        LLR\
        \ p-value:                 2.927e-98\n====================================================================================\n\
        \                       coef    std err          z      P>|z|      [0.025\
        \      0.975]\n------------------------------------------------------------------------------------\n\
        Intercept           -5.1120      0.250    -20.478      0.000      -5.601 \
        \     -4.623\nage_of_head          0.1294      0.008     16.962      0.000\
        \       0.114       0.144\nincome           -7.381e-06      1e-06     -7.354\
        \      0.000   -9.35e-06   -5.41e-06\ncars                 0.3869      0.049\
        \      7.923      0.000       0.291       0.483\nresidential_sqft -5.001e-06\
        \   8.33e-07     -6.006      0.000   -6.63e-06   -3.37e-06\n===================================================================================="
    tables:
    - households
    - buildings
    - parcels
    tags: null
    type: BinaryLogitStep

test-2:
    model:
        fit_filters: null
        fit_parameters:
            Coefficient:
                Intercept: 40.09871283035528
                ave_income: 0.23072273780443825
                distance_to_freeway: 1.7180369445701138e-05
                jobs_3000m: 0.0052401490489375055
                parcel_acres: -1.3332502420922587
                population_400m: -0.32329211786063883
                year_built: -0.01829513014570837
            Std. Error:
                Intercept: 1.4425492135860816
                ave_income: 0.059241099415382255
                distance_to_freeway: 1.3879035363021292e-05
                jobs_3000m: 0.0023354199740452226
                parcel_acres: 0.06486249313570111
                population_400m: 0.020305866818345758
                year_built: 0.0006713350100920479
            T-Score:
                Intercept: 27.79711946927103
                ave_income: 3.894639702526012
                distance_to_freeway: 1.2378648080597718
                jobs_3000m: 2.243771615886692
                parcel_acres: -20.55502614281136
                population_400m: -15.921118795507603
                year_built: -27.251863630946183
        fit_rsquared: 0.4805086622299135
        fit_rsquared_adj: 0.4790755826774442
        fitted: true
        model_expression: np.log1p(res_price_per_sqft) ~ parcel_acres + year_built
            + ave_income + distance_to_freeway + population_400m + jobs_3000m
        model_type: regression
        name: RegressionStep-20180211-220919
        predict_filters: null
        ytransform: np.exp
    model_expression: np.log1p(res_price_per_sqft) ~ parcel_acres + year_built + ave_income
        + distance_to_freeway + population_400m + jobs_3000m
    name: test-2
    out_fname: fitted_price
    tables:
    - buildings
    - parcels
    - nodes
    tags:
    - residential-price-hedonic
    - sam
    - '201802'
    type: RegressionStep

test-1:
    model:
        fit_filters: null
        fit_parameters:
            Coefficient:
                Intercept: 40.09871283035528
                ave_income: 0.23072273780443825
                distance_to_freeway: 1.7180369445701138e-05
                jobs_3000m: 0.0052401490489375055
                parcel_acres: -1.3332502420922587
                population_400m: -0.32329211786063883
                year_built: -0.01829513014570837
            Std. Error:
                Intercept: 1.4425492135860816
                ave_income: 0.059241099415382255
                distance_to_freeway: 1.3879035363021292e-05
                jobs_3000m: 0.0023354199740452226
                parcel_acres: 0.06486249313570111
                population_400m: 0.020305866818345758
                year_built: 0.0006713350100920479
            T-Score:
                Intercept: 27.79711946927103
                ave_income: 3.894639702526012
                distance_to_freeway: 1.2378648080597718
                jobs_3000m: 2.243771615886692
                parcel_acres: -20.55502614281136
                population_400m: -15.921118795507603
                year_built: -27.251863630946183
        fit_rsquared: 0.4805086622299135
        fit_rsquared_adj: 0.4790755826774442
        fitted: true
        model_expression: np.log1p(res_price_per_sqft) ~ parcel_acres + year_built
            + ave_income + distance_to_freeway + population_400m + jobs_3000m
        model_type: regression
        name: RegressionStep-20180211-220749
        predict_filters: null
        ytransform: np.exp
    model_expression: np.log1p(res_price_per_sqft) ~ parcel_acres + year_built + ave_income
        + distance_to_freeway + population_400m + jobs_3000m
    name: test-1
    out_fname: fitted_price
    tables:
    - buildings
    - parcels
    - nodes
    tags:
    - residential-price-hedonic
    - sam
    - '201802'
    type: RegressionStep

RegressionStep-20180214-210159:
    model:
        fit_filters: null
        fit_parameters:
            Coefficient:
                Intercept: 40.09871283035528
                ave_income: 0.23072273780443825
                distance_to_freeway: 1.7180369445701138e-05
                jobs_3000m: 0.0052401490489375055
                parcel_acres: -1.3332502420922587
                population_400m: -0.32329211786063883
                year_built: -0.01829513014570837
            Std. Error:
                Intercept: 1.4425492135860816
                ave_income: 0.059241099415382255
                distance_to_freeway: 1.3879035363021292e-05
                jobs_3000m: 0.0023354199740452226
                parcel_acres: 0.06486249313570111
                population_400m: 0.020305866818345758
                year_built: 0.0006713350100920479
            T-Score:
                Intercept: 27.79711946927103
                ave_income: 3.894639702526012
                distance_to_freeway: 1.2378648080597718
                jobs_3000m: 2.243771615886692
                parcel_acres: -20.55502614281136
                population_400m: -15.921118795507603
                year_built: -27.251863630946183
        fit_rsquared: 0.4805086622299135
        fit_rsquared_adj: 0.4790755826774442
        fitted: true
        model_expression: np.log1p(res_price_per_sqft) ~ parcel_acres + year_built
            + ave_income + distance_to_freeway + population_400m + jobs_3000m
        model_type: regression
        name: RegressionStep-20180214-210159
        predict_filters: null
        ytransform: np.exp
    model_expression: np.log1p(res_price_per_sqft) ~ parcel_acres + year_built + ave_income
        + distance_to_freeway + population_400m + jobs_3000m
    name: RegressionStep-20180214-210159
    out_fname: fitted_price
    tables:
    - buildings
    - parcels
    - nodes
    tags:
    - residential-price-hedonic
    - sam
    - '201802'
    type: RegressionStep

BinaryLogitStep-20180314-211201:
    filters:
    - age_of_head < 40
    fitted_parameters:
    - -5.111984721917692
    - 0.12937080499546547
    - -7.380928627907898e-06
    - 0.386911210479455
    - -5.0005270183615935e-06
    model_expression: children ~ age_of_head + income + cars + residential_sqft
    name: BinaryLogitStep-20180314-211201
    out_column: null
    out_tables: null
    out_transform: null
    out_value_false: nothing
    out_value_true: -1
    summary_table: "                           Logit Regression Results          \
        \                 \n==============================================================================\n\
        Dep. Variable:               children   No. Observations:                \
        \ 4776\nModel:                          Logit   Df Residuals:            \
        \         4771\nMethod:                           MLE   Df Model:        \
        \                    4\nDate:                Wed, 14 Mar 2018   Pseudo R-squ.:\
        \                 0.08767\nTime:                        21:12:01   Log-Likelihood:\
        \                -2393.6\nconverged:                       True   LL-Null:\
        \                       -2623.6\n                                        LLR\
        \ p-value:                 2.927e-98\n====================================================================================\n\
        \                       coef    std err          z      P>|z|      [0.025\
        \      0.975]\n------------------------------------------------------------------------------------\n\
        Intercept           -5.1120      0.250    -20.478      0.000      -5.601 \
        \     -4.623\nage_of_head          0.1294      0.008     16.962      0.000\
        \       0.114       0.144\nincome           -7.381e-06      1e-06     -7.354\
        \      0.000   -9.35e-06   -5.41e-06\ncars                 0.3869      0.049\
        \      7.923      0.000       0.291       0.483\nresidential_sqft -5.001e-06\
        \   8.33e-07     -6.006      0.000   -6.63e-06   -3.37e-06\n===================================================================================="
    tables:
    - households
    - buildings
    - parcels
    tags: null
    type: BinaryLogitStep

BinaryLogitStep-20180314-213137:
    filters:
    - age_of_head < 40
    fitted_parameters:
    - -5.111984721917692
    - 0.12937080499546547
    - -7.380928627907898e-06
    - 0.386911210479455
    - -5.0005270183615935e-06
    model_expression: children ~ age_of_head + income + cars + residential_sqft
    name: BinaryLogitStep-20180314-213137
    out_column: null
    out_tables: null
    out_transform: null
    out_value_false: nothing
    out_value_true: -1
    summary_table: "                           Logit Regression Results          \
        \                 \n==============================================================================\n\
        Dep. Variable:               children   No. Observations:                \
        \ 4776\nModel:                          Logit   Df Residuals:            \
        \         4771\nMethod:                           MLE   Df Model:        \
        \                    4\nDate:                Wed, 14 Mar 2018   Pseudo R-squ.:\
        \                 0.08767\nTime:                        21:31:37   Log-Likelihood:\
        \                -2393.6\nconverged:                       True   LL-Null:\
        \                       -2623.6\n                                        LLR\
        \ p-value:                 2.927e-98\n====================================================================================\n\
        \                       coef    std err          z      P>|z|      [0.025\
        \      0.975]\n------------------------------------------------------------------------------------\n\
        Intercept           -5.1120      0.250    -20.478      0.000      -5.601 \
        \     -4.623\nage_of_head          0.1294      0.008     16.962      0.000\
        \       0.114       0.144\nincome           -7.381e-06      1e-06     -7.354\
        \      0.000   -9.35e-06   -5.41e-06\ncars                 0.3869      0.049\
        \      7.923      0.000       0.291       0.483\nresidential_sqft -5.001e-06\
        \   8.33e-07     -6.006      0.000   -6.63e-06   -3.37e-06\n===================================================================================="
    tables:
    - households
    - buildings
    - parcels
    tags: null
    type: BinaryLogitStep

hlcm1:
    alternatives:
    - buildings
    - nodes
    choosers: households
    model:
        alts_fit_filters: null
        alts_predict_filters: null
        choice_column: null
        choice_mode: individual
        choosers_fit_filters: null
        choosers_predict_filters: null
        estimation_sample_size: null
        fit_parameters:
            Coefficient:
                jobs_1500m: 0.34581936115720685
                res_price_per_sqft: -0.007174190659138939
            Std. Error:
                jobs_1500m: 0.008172372255171383
                res_price_per_sqft: 6.617589518178617e-05
            T-Score:
                jobs_1500m: 42.3156643333735
                res_price_per_sqft: -108.41093481895984
        fitted: true
        interaction_predict_filters: null
        log_likelihoods:
            convergence: -34575.48735554272
            'null': -39898.7226323586
            ratio: 0.13341868926146117
        model_expression: res_price_per_sqft + jobs_1500m
        model_type: discretechoice
        name: hlcm1
        prediction_sample_size: null
        probability_mode: full_product
        sample_size: 50
    model_expression: res_price_per_sqft + jobs_1500m
    name: hlcm1
    out_fname: fitted_hlcm
    sample_size: 50
    tags:
    - hlcm
    - max
    - '201802'
    type: MNLDiscreteChoiceStep
